changelog:
  categories:
    -
      labels:
        - dev::build
      title: Build
    -
      labels:
        - dev::CI
      title: Continuous Integration
    -
      labels:
        - dev::docs
      title: Docs
    -
      labels:
        - dev::feat
      title: Feat
    -
      labels:
        - dev::fix
      title: Fix
    -
      labels:
        - dev::Perf
      title: Perf
    -
      labels:
        - dev::refactor
      title: Refactor
    -
      labels:
        - dev::test
      title: Test
