codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,files,footer
  require_changes: false
coverage:
  precision: 2
  range: 70...100
  round: down
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      macro: no
      method: no
