#!/bin/bash
set -eu
set -o errexit
set -o pipefail
set -o nounset

echo '+cargo check'
cargo check --all-features --workspace

echo '+cargo test'
cargo test --all-features --workspace

echo '+cargo install audit'
cargo install cargo-audit

echo '+cargo audit'
cargo audit
