# BEGIN project-specific configuration

.fip_api: &fip_api
  variables:
    DOCKERFILE: "fip_api/Dockerfile"
    IMAGE_NAME: "fip-api"
    PACKAGE: "fip_api"
  only:
    changes:
      - "fip_api/**/*"

# END project-specific configuration

# BEGIN actual pipeline definition

build_1:fip_api:
  dependencies: []
  extends:
    - ".build"
    - ".fip_api"
    - ".target_1"
  needs: []

build_2:fip_api:
  dependencies: []
  extends:
    - ".build"
    - ".fip_api"
    - ".target_2"
  needs: []

build_3:fip_api:
  dependencies: []
  extends:
    - ".build"
    - ".fip_api"
    - ".target_3"
  needs: []

test:fip_api:
  dependencies: []
  extends:
    - ".test"
    - ".fip_api"
  needs: []

coverage:fip_api:
  dependencies: []
  extends:
    - ".coverage"
    - ".fip_api"
  needs: []

upload_1:fip_api:
  dependencies:
    - "build_1:fip_api"
  extends:
    - ".fip_api"
    - ".target_1"
    - ".upload"
  needs:
    - "build_1:fip_api"
    # - "build_2:fip_api"
    # - "build_3:fip_api"

upload_2:fip_api:
  dependencies:
    - "build_2:fip_api"
  extends:
    - ".fip_api"
    - ".target_2"
    - ".upload"
  needs:
    # - "build_1:fip_api"
    - "build_2:fip_api"
    # - "build_3:fip_api"

upload_3:fip_api:
  dependencies:
    - "build_3:fip_api"
  extends:
    - ".fip_api"
    - ".target_3"
    - ".upload"
  needs:
    # - "build_1:fip_api"
    # - "build_2:fip_api"
    - "build_3:fip_api"

release:fip_api:
  dependencies: []
  extends:
    - ".release"
    - ".fip_api"
  needs:
    # - "upload_1:fip_api"
    # - "upload_2:fip_api"
    - "upload_3:fip_api"

documentation:fip_api:
  dependencies: []
  extends:
    - ".documentation"
    - ".fip_api"
  needs: []

pages:fip_api:
  dependencies:
    - "coverage:fip_api"
    - "documentation:fip_api"
  extends:
    - ".pages"
    - ".fip_api"
  needs:
    - "coverage:fip_api"
    - "documentation:fip_api"

deploy:fip_api:
  dependencies: []
  extends:
    - ".deploy"
    - ".fip_api"
  needs:
    - "test:fip_api"

# END actual pipeline definition
