//! TODO: documentation

fn main() {
    tonic_build::configure()
        .build_client(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        // .extern_path(".fip.api", "client")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .proto_path("crate::api::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["api_api.proto"], &["../fip_api/proto"])
        .unwrap();

    tonic_build::configure()
        .build_client(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        // .extern_path(".fip.auth", "client")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .proto_path("crate::auth::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["api_auth.proto"], &["../fip_api/proto"])
        .unwrap();

    tonic_build::configure()
        .build_client(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        .extern_path(".fip.at", "client")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .proto_path("crate::at::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["api_at.proto"], &["proto", "../fip_at/proto"])
        .unwrap();
    tonic_build::configure()
        .build_client(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        .extern_path(".fip.jwks", "client")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .proto_path("crate::jwks::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["api_jwks.proto"], &["proto", "../fip_jwks/proto"])
        .unwrap();
    tonic_build::configure()
        .build_client(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        .extern_path(".fip.rt", "client")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .proto_path("crate::rt::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["api_rt.proto"], &["proto", "../fip_rt/proto"])
        .unwrap();
    tonic_build::configure()
        .build_client(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        .extern_path(".fip.user", "client")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .proto_path("crate::user::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["api_user.proto"], &["proto", "../fip_user/proto"])
        .unwrap();

    tonic_build::configure()
        .build_server(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        // .extern_path(".fip.at", "server")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .proto_path("crate::api::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["at.proto"], &["../fip_at/proto"])
        .unwrap();
    tonic_build::configure()
        .build_server(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        // .extern_path(".fip.jwks", "server")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .proto_path("crate::api::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["jwks.proto"], &["../fip_jwks/proto"])
        .unwrap();
    tonic_build::configure()
        .build_server(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        // .extern_path(".fip.rt", "server")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .proto_path("crate::api::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["rt.proto"], &["../fip_rt/proto"])
        .unwrap();
    tonic_build::configure()
        .build_server(false)
        .client_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .client_mod_attribute(".", "")
        // .extern_path(".fip.user", "server")
        .field_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .proto_path("crate::api::proto")
        .server_attribute(".", "#[doc = r\" TODO: documentation\"]")
        // .server_mod_attribute(".", "")
        .type_attribute(".", "#[doc = r\" TODO: documentation\"]")
        .compile(&["user.proto"], &["../fip_user/proto"])
        .unwrap();
}
