description: Extract release metadata from the tag
inputs:
  git-ref:
    description: The git ref (i.e. starting with refs/tags/)
    required: true
name: Release tag meta
outputs:
  name:
    description: The release name (without the refs/heads/v prefix)
  tag:
    description: The git tag (without the refs/tags/ prefix)
runs:
  args:
    - ${{ inputs.git-ref }}
  image: Dockerfile
  using: docker
