description: Extract release metadata from the tag
inputs:
  git-ref:
    description: "The git ref (i.e. starting with refs/tags)"
    required: true
name: release-tag-meta
outputs:
  tag:
    description: "The git tag (without the refs prefix)"
  name:
    description: "The release name"
runs:
  args:
    - ${{ inputs.git-ref }}
  image: Dockerfile
  using: docker
