jobs:
  check:
    container:
      image: docker://rust:1.55.0-buster
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      -
        run: make check fmt-check
    timeout-minutes: 5
  audit:
    continue-on-error: ${{ matrix.checks == "advisories" }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      -
        uses: EmbarkStudios/cargo-deny-action@0ca727bbae7b7b578b9a5f98186caac35aa2a00d
        with:
          command: check ${{ matrix.checks }}
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    timeout-minutes: 5
  clippy:
    container:
      image: docker://rust:1.55.0-buster
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      -
        run: make clippy
    timeout-minutes: 5
name: Check
on:
  pull_request: {}
