jobs:
  check:
    container:
      image: docker://rust:1.56.0-bullseye
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        run: make check fmt-check
    timeout-minutes: 5
  audit:
    continue-on-error: ${{ matrix.checks == "advisories" }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        uses: EmbarkStudios/cargo-deny-action@0ca727bbae7b7b578b9a5f98186caac35aa2a00d
        with:
          command: check ${{ matrix.checks }}
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    timeout-minutes: 5
  clippy:
    container:
      image: docker://rust:1.56.0-bullseye
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        run: make clippy
    timeout-minutes: 5
name: Check
on:
  pull_request: {}
