env:
  CARGO_TERM_COLOR: always
jobs:
  package:
    name: Package (${{ matrix.architecture }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        id: release-tag-meta
        name: Release Tag Meta
        uses: ./.github/actions/release-tag-meta
        with:
          git-ref: ${{ github.ref }}
      -
        env:
          ARCHITECTURE: ${{ matrix.architecture }}
          CARGO: cross
          PACKAGE: fip_api
          RELEASE: --release
          STRIP: ${{ matrix.strip }}
          TARGET: ${{ matrix.target }}
          VERSION: ${{ steps.release-tag-meta.outputs.tag }}
        name: Package
        uses: ./.github/actions/package
        with:
          args: release
          entrypoint: make
      -
        name: Upload Artifacts
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
        with:
          path: release/*
    strategy:
      matrix:
        include:
          -
            architecture: arm64
            strip: aarch64-linux-gnu-strip
            target: aarch64-unknown-linux-musl
          -
            architecture: armv7
            strip: arm-linux-gnueabihf-strip
            target: armv7-unknown-linux-musleabihf
          -
            architecture: amd64
            strip: strip
            target: x86_64-unknown-linux-musl
        target:
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    timeout-minutes: 30
  release:
    name: GitHub Release
    needs:
      - package
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        id: release-tag-meta
        name: Release Tag Meta
        uses: ./.github/actions/release-tag-meta
        with:
          git-ref: ${{ github.ref }}
      -
        name: Download Artifacts
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60
        with:
          path: artifact
      -
        name: Generate Changelog
        run: echo "# CHANGELOG" > ${{ github.workspace }}-CHANGELOG.md
        shell: bash
      -
        name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: artifact/**/*
          generate_release_notes: true
          name: ${{ steps.release-tag-meta.outputs.name }}
          prerelease: ${{ steps.release-tag-meta.outputs.prerelease }}
          tag_name: ${{ steps.release-tag-meta.outputs.tag }}
          token: ${{ secrets.PACKAGE_REGISTRY }}
    timeout-minutes: 5
name: Push Tag V
on:
  push:
    tags:
      - v*.*.*
