env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-docker-image:
    name: Build and Publish Docker Image
    permissions:
      # actions: write
      # checks: write
      contents: read
      # deployments: write
      # issues: write
      packages: write
      # pull-requests: write
      # repository-projects: write
      # security-events: write
      # statuses: write
      # id-token: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          # password: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.PACKAGE_REGISTRY }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      -
        name: Extract Metadata (Tags, Labels) for Docker
        id: metadata
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./fip_api
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
name: Release Published
on:
  release:
    types:
      - published
